[01주차 조예빈] 백준12845번_모두의마블
dsa-master/dsa-study-2023 pull request #4
Opened 2023-10-12 06:47 UTC by Jyebin

## 🔎 문제 소개

-   **링크**: https://www.acmicpc.net/problem/12845
-   **제목**: 모두의마블
-   **분류**:
    -   (예시) greedy 알고리즘

## 🖊️ 풀이

-   **시간 복잡도**: O(n)
-   **입력의 크기**:
    -   n

---

2023-10-12 07:55 UTC, hepheir requested changes

2023-10-12 07:55 UTC, hepheir commented on .DS_Store
불필요한 파일입니다 제거해주세요!

2023-10-12 07:55 UTC, hepheir commented on 00주차 (예시)/.DS_Store
불필요한 파일입니다 제거해주세요!

2023-10-12 07:55 UTC, hepheir commented on 00주차 (예시)/foo/.DS_Store
불필요한 파일입니다 제거해주세요!

2023-10-14 07:02 UTC, hepheir requested changes

2023-10-14 07:02 UTC, hepheir commented on 01주차:조예빈/num12845.java
파일명을 `01주차:조예빈/num12845.java` 말고 `01주차/조예빈/num12845.java`으로 바꿔주세요!

```diff
-01주차:조예빈/num12845.java
+01주차/조예빈/num12845.java
```

2023-10-14 10:36 UTC, hepheir commented
제출하시느라 고생하셨습니다 :) 요청드린 수정사항만 확인 후 반영부탁드릴께요!

2023-10-15 07:49 UTC, pmsu2007 approved these changes

2023-10-15 07:49 UTC, pmsu2007 commented on 01주차:조예빈/num12845.java
> +        }
가장 레벨이 높은 카드와 합치기만 하면 된다는 것을 이용한 풀이인가요?

2023-10-15 10:23 UTC, Eunji1217 approved these changes

2023-10-15 10:23 UTC, Eunji1217 commented on 01주차:조예빈/num12845.java
> +        }
오 딱 저도 문제 보고 그렇지 않을까란 생각을 하긴 했는데 그리디스러운 문제네요

2023-10-22 02:47 UTC, Jyebin commented on 01주차:조예빈/num12845.java
> +        }
네 마자여 젤 레벨이 높은 카드랑 합치기만 하면 된다고 생각했어요!

2023-10-22 03:53 UTC, merged